fix: update snapshot

diff --git a/.github/workflows/update-snapshot.yml b/.github/workflows/update-snapshot.yml
--- a/.github/workflows/update-snapshot.yml
+++ b/.github/workflows/update-snapshot.yml
@@ -31,7 +31,7 @@ jobs:
       stylelint: ${{ steps.filter.outputs.stylelint }}
 
     steps:
-      - name: Check changed packages (PR Review Approved)
+      - name: Check changed packages (PR Comment)
         uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
         id: filter
         with:
@@ -43,14 +43,35 @@ jobs:
             stylelint:
               - 'packages/stylelint-config/**'
 
-  update-snapshot:
+  check-target-packages:
     needs: filter-pr
     runs-on: ubuntu-24.04
-    env:
-      ESLINT_CHANGED: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.eslint == 'true' || needs.filter-pr.outputs.eslint == 'true' }}
-      PRETTIER_CHANGED: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.prettier == 'true' || needs.filter-pr.outputs.prettier == 'true' }}
-      STYLELINT_CHANGED: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.stylelint == 'true' || needs.filter-pr.outputs.stylelint == 'true' }}
-    if: ${{ github.env.ESLINT_CHANGED == 'true' || github.env.PRETTIER_CHANGED == 'true' || github.env.STYLELINT_CHANGED == 'true' }}
+    outputs:
+      eslint: ${{ steps.check.outputs.eslint }}
+      prettier: ${{ steps.check.outputs.prettier }}
+      stylelint: ${{ steps.check.outputs.stylelint }}
+
+    steps:
+      - name: Check changed packages
+        id: check
+        run: |
+          if [ ${{ github.event_name == 'workflow_dispatch' }} ]; then
+            echo "eslint=${{ github.event.inputs.eslint }}" >> $GITHUB_OUTPUT
+            echo "prettier=${{ github.event.inputs.prettier }}" >> $GITHUB_OUTPUT
+            echo "stylelint=${{ github.event.inputs.stylelint }}" >> $GITHUB_OUTPUT
+          else if [ ${{ github.event_name == 'issue_comment' }} ]; then
+            echo "eslint=${{ needs.filter-pr.outputs.eslint }}" >> $GITHUB_OUTPUT
+            echo "prettier=${{ needs.filter-pr.outputs.prettier }}" >> $GITHUB_OUTPUT
+            echo "stylelint=${{ needs.filter-pr.outputs.stylelint }}" >> $GITHUB_OUTPUT
+          else
+            echo "::error::Workflow called by unexpected event."
+            exit 1
+          fi
+
+  update-snapshot:
+    needs: check-target-packages
+    if: needs.check-target-packages.outputs.eslint == 'true' || needs.check-target-packages.outputs.prettier == 'true' || needs.check-target-packages.outputs.stylelint == 'true'
+    runs-on: ubuntu-24.04
     permissions:
       contents: write
       pull-requests: write
@@ -77,15 +98,15 @@ jobs:
         run: pnpm install --frozen-lockfile
 
       - name: Update ESLint Config Snapshot
-        if: github.env.ESLINT_CHANGED == 'true'
+        if: needs.check-target-packages.outputs.eslint == 'true'
         run: pnpm run test --project eslint-config -- -u
 
       - name: Update Prettier Config Snapshot
-        if: github.env.PRETTIER_CHANGED == 'true'
+        if: needs.check-target-packages.outputs.prettier == 'true'
         run: pnpm run test --project prettier-config -- -u
 
       - name: Update Stylelint Config Snapshot
-        if: github.env.STYLELINT_CHANGED == 'true'
+        if: needs.check-target-packages.outputs.stylelint == 'true'
         run: pnpm run test --project stylelint-config -- -u
 
       - name: Create change summary markdown
@@ -93,13 +114,13 @@ jobs:
           set -eu
           echo "## 🚚 Updated snapshots" >> CHANGES.md
 
-          if [ ${{ github.env.ESLINT_CHANGED }} == 'true' ]; then
+          if [ ${{ needs.check-target-packages.outputs.eslint }} == 'true' ]; then
               echo "- ESLint" >> CHANGES.md
           fi
-          if [ ${{ github.env.PRETTIER_CHANGED }} == 'true' ]; then
+          if [ ${{ needs.check-target-packages.outputs.prettier }} == 'true' ]; then
               echo "- Prettier" >> CHANGES.md
           fi
-          if [ ${{ github.env.STYLELINT_CHANGED }} == 'true' ]; then
+          if [ ${{ needs.check-target-packages.outputs.stylelint }} == 'true' ]; then
               echo "- Stylelint" >> CHANGES.md
           fi
 
