fix: use github app

diff --git a/.github/workflows/update-snapshot.yml b/.github/workflows/update-snapshot.yml
--- a/.github/workflows/update-snapshot.yml
+++ b/.github/workflows/update-snapshot.yml
@@ -25,8 +25,9 @@ jobs:
   filter-packages:
     name: Check Changed Packages
     runs-on: ubuntu-24.04
+    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && !contains(github.event.comment.user.name, 'bot') && contains(github.event.comment.body, '/update-snapshot')
     outputs:
-      head_ref: ${{ fromJson(steps.pr-request.outputs.data).head.ref }}
+      head_ref: ${{ fromJson(steps.pr-request.outputs.data).head.ref  }}
       eslint: ${{ false || steps.filter.outputs.eslint }}
       prettier: ${{ false || steps.filter.outputs.prettier }}
       stylelint: ${{ false || steps.filter.outputs.stylelint }}
@@ -64,7 +65,6 @@ jobs:
           ref: ${{ fromJson(steps.pr-request.outputs.data).head.ref }}
 
       - name: Check changed packages (PR Comment)
-        if: github.event_name == 'issue_comment' && github.event.issue.pull_request && !contains(github.event.comment.user.name, 'bot') && contains(github.event.comment.body, '/update-snapshot')
         uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
         id: filter
         with:
@@ -79,12 +79,14 @@ jobs:
 
   check-target-packages:
     name: Check target packages
+    if: always()
     needs: filter-packages
     runs-on: ubuntu-24.04
     outputs:
       eslint: ${{ steps.check.outputs.eslint }}
       prettier: ${{ steps.check.outputs.prettier }}
       stylelint: ${{ steps.check.outputs.stylelint }}
+      head_ref: ${{ steps.set-head-ref.outputs.head_ref }}
 
     steps:
       - name: Check target packages
@@ -103,9 +105,21 @@ jobs:
             exit 1
           fi
 
+      - name: Set head ref
+        id: set-head-ref
+        run: |
+          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+            echo "head_ref=${{ github.ref }}" >> $GITHUB_OUTPUT
+          elif [ ${{ github.event_name }} == 'issue_comment'  ]; then
+            echo "head_ref=${{ needs.filter-packages.outputs.head_ref }}" >> $GITHUB_OUTPUT
+          else
+            echo "::error::Workflow called by unexpected event."
+            exit 1
+          fi
+
   update-snapshot:
     name: Update Snapshot
-    needs: [check-target-packages, filter-packages]
+    needs: check-target-packages
     if: needs.check-target-packages.outputs.eslint == 'true' || needs.check-target-packages.outputs.prettier == 'true' || needs.check-target-packages.outputs.stylelint == 'true'
     runs-on: ubuntu-24.04
     permissions:
@@ -117,12 +131,28 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
         with:
-          ref: ${{ needs.filter-packages.outputs.head_ref}}
+          ref: ${{ needs.check-target-packages.outputs.head_ref }}
+
+      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
+        id: app-token
+        with:
+          app-id: ${{ vars.ACTIONS_MIKU_APP_ID }}
+          private-key: ${{ secrets.ACTIONS_MIKU_PRIVATE_KEY }}
+
+      - name: Get GitHub App User ID
+        id: get-user-id
+        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
 
       - name: Configure Git Identity
         run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
+          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
+
+          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+            git switch -c "bot/update-snapshot-$(TZ=UTC-9 date +'%Y%m')-${SHA:0:7}"
+          fi
 
       - run: corepack enable pnpm
 
@@ -163,15 +193,14 @@ jobs:
           fi
 
       - name: Commit and Push Changes
-        if: github.event_name == 'issue_comment'
         run: |
           set -eu
           git add .
           git reset -- CHANGES.md
           git commit -m "chore: update snapshot (github-actions)"
-          git push
+          git push origin HEAD
 
-      - name: Comment to PR
+      - name: Comment to PR (Issue Comment)
         if: github.event_name == 'issue_comment'
         run: |
           set -eu
@@ -183,12 +212,17 @@ jobs:
           gh pr comment ${{ github.event.issue.number }} --body-file CHANGES.md --edit-last \
             || gh pr comment ${{ github.event.issue.number}} --body-file CHANGES.md
         env:
-          GH_TOKEN: ${{ github.token }}
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
 
-      - name: Create Pull Request
+      - name: Create Pull Request (Workflow Dispatch)
         if: github.event_name == 'workflow_dispatch'
-        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
-        with:
-          commit-message: "chore: update snapshot (github-actions)"
-          title: "Update Snapshot"
-          body-path: CHANGES.md
+        run: |
+          set -eu
+          if [ ! -f CHANGES.md ]; then
+            echo "::warn::comment body not found."
+            exit 0
+          fi
+
+          gh pr create --base "main" --body-file CHANGES.md --title "update snapshot (github-actions)"
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
